<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="5" skipped="2" tests="16" time="0.166" timestamp="2022-03-29T16:59:26.779158" hostname="Vira"><testcase classname="test_pycalculator" name="test_add[3-2-5]" time="0.001" /><testcase classname="test_pycalculator" name="test_add[4-2-6]" time="0.001" /><testcase classname="test_pycalculator" name="test_add[5-5-10]" time="0.001" /><testcase classname="test_pycalculator" name="test_add[5-5-9]" time="0.001"><skipped type="pytest.xfail" message="" /></testcase><testcase classname="test_pycalculator" name="test_sub[3-2-1]" time="0.001" /><testcase classname="test_pycalculator" name="test_sub[4-2-2]" time="0.001" /><testcase classname="test_pycalculator" name="test_sub[5-5-0]" time="0.001" /><testcase classname="test_pycalculator" name="test_sub[5-5-9]" time="0.001"><skipped type="pytest.xfail" message="" /></testcase><testcase classname="test_pycalculator" name="test_mult[3-2-6]" time="0.001"><failure message="AttributeError: module 'Calculator' has no attribute 'mult'">a = 3, b = 2, c = 6

    @pytest.mark.parametrize("a,b,c",[(3,2,6),(4,2,8),(5,5,25),(5,5,9)])
    def test_mult(a,b,c):
        # x=10
        # y=20
&gt;       r=Calculator.mult(a, b)
E       AttributeError: module 'Calculator' has no attribute 'mult'

test_pycalculator.py:22: AttributeError</failure></testcase><testcase classname="test_pycalculator" name="test_mult[4-2-8]" time="0.001"><failure message="AttributeError: module 'Calculator' has no attribute 'mult'">a = 4, b = 2, c = 8

    @pytest.mark.parametrize("a,b,c",[(3,2,6),(4,2,8),(5,5,25),(5,5,9)])
    def test_mult(a,b,c):
        # x=10
        # y=20
&gt;       r=Calculator.mult(a, b)
E       AttributeError: module 'Calculator' has no attribute 'mult'

test_pycalculator.py:22: AttributeError</failure></testcase><testcase classname="test_pycalculator" name="test_mult[5-5-25]" time="0.001"><failure message="AttributeError: module 'Calculator' has no attribute 'mult'">a = 5, b = 5, c = 25

    @pytest.mark.parametrize("a,b,c",[(3,2,6),(4,2,8),(5,5,25),(5,5,9)])
    def test_mult(a,b,c):
        # x=10
        # y=20
&gt;       r=Calculator.mult(a, b)
E       AttributeError: module 'Calculator' has no attribute 'mult'

test_pycalculator.py:22: AttributeError</failure></testcase><testcase classname="test_pycalculator" name="test_mult[5-5-9]" time="0.001"><failure message="AttributeError: module 'Calculator' has no attribute 'mult'">a = 5, b = 5, c = 9

    @pytest.mark.parametrize("a,b,c",[(3,2,6),(4,2,8),(5,5,25),(5,5,9)])
    def test_mult(a,b,c):
        # x=10
        # y=20
&gt;       r=Calculator.mult(a, b)
E       AttributeError: module 'Calculator' has no attribute 'mult'

test_pycalculator.py:22: AttributeError</failure></testcase><testcase classname="test_pycalculator" name="test_div[3-2-1.5]" time="0.001" /><testcase classname="test_pycalculator" name="test_div[4-2-2]" time="0.001" /><testcase classname="test_pycalculator" name="test_div[5-5-1]" time="0.001" /><testcase classname="test_pycalculator" name="test_div[5-5-9]" time="0.001"><failure message="assert 1.0 == 9">a = 5, b = 5, c = 9

    @pytest.mark.parametrize("a,b,c",[(3,2,1.5),(4,2,2),(5,5,1),(5,5,9)])
    def test_div(a,b,c):
        # x=10
        # y=20
        r=Calculator.div(a, b)
&gt;       assert r == c
E       assert 1.0 == 9

test_pycalculator.py:30: AssertionError</failure></testcase></testsuite></testsuites>